name: update-pip-constraints
description: Update PyPI constraints files for a specific version of Python

inputs:
  python-version:
    description: Python version to run update-pip-constraints with
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - run: pip install git+https://github.com/ComPWA/update-pip-constraints@main
      shell: bash
    - run: update-pip-constraints
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        path: .constraints/py${{ inputs.python-version }}.txt
